### ISSUE TITLE
Remove an empty set from a power set

### ISSUE THREAD

**Issue by nrryuya** [cbc-casper/cbc-casper-paper#17]
AFAIK, the general meaning of `A \ B` is a difference between a set `A` and a set `B`. 

So in the function signature of estimators, I guess `P(C) \ {∅}` is correct.
![image](https://user-images.githubusercontent.com/22876645/51011410-c8884a00-159b-11e9-8204-e78fe61260a9.png)

**Comment by naterush** [comment]
Good catch. P(C) \ emptyset would just be P(C) :)
