### ISSUE TITLE
Need to correct to either "a protocol's states" or "a protocol state"

### ISSUE THREAD

**Issue by pyskell** [cbc-casper/cbc-casper-paper#7]
https://github.com/cbc-casper/cbc-casper-paper/blob/96a94e568c4f6346d69f880e228cf8bc2f76a602/cbc-casper-paper-draft.tex#L342

**Comment by vladzamfir** [comment]
addressed by commit https://github.com/cbc-casper/cbc-casper-paper/commit/ce5c17c4f38c6b0b5f78277b0425e6406d457f8a
